### ISSUE TITLE
Question: What version of Gtoolkit are you running this on?

### ISSUE THREAD

**Issue by z3t0** [seandenigris/Dynabook#19]
I am hitting the following error when using the latest gtoolkit on windows. The version is v1.0.130

```
Package ComputerWorld-Mac depends on the following classes:
  CustomHelp
You must resolve these dependencies before you will be able to load these definitions: 
  ComputerWorldHelp
  ComputerWorldHelp>>#bookName
  ComputerWorldHelp>>#introduction
  ComputerWorldHelp>>#pages
```

I can provide more info if needed, and sorry if my question is basic.
I just came across your project and was really interested in seeing if I could get it running. Building something in the spirit of the Dynabook has been a long-time passion of mine.

Thank you for your time.

**Comment by z3t0** [comment]
Sorry, it seems to have fixed itself after running the install commands a second time.

**Comment by seandenigris** [comment]
I think GT may have just upgraded from Pharo 10 to 11, which may be the cause. If it happens again you should be able to safely proceed past the warning. I’ll be porting shortly but I’ma free GT versions back

**Comment by seandenigris** [comment]
Feel free to ask more questions! I’m active on GT Discord as well
