### ISSUE TITLE
Dynabook-Persistence: Instance of FLSerializer did not understand #object:

### ISSUE THREAD

**Issue by RalfBarkow** [seandenigris/Dynabook#8]
In a DynabookDB class, I click `Save Repository` in order to get my 1 copies of 1 works in LlLibrary saved:
<img width="1312" alt="Bildschirmfoto 2022-02-20 um 12 47 50" src="https://user-images.githubusercontent.com/1205477/154841074-c0c802b6-79bf-4971-9df1-5a0a16d995db.png">

**Comment by seandenigris** [comment]
You probably have to upgrade fuel to latest.

**Comment by seandenigris** [comment]
Or IIRC you can configure the SP serializer to whatever version of Fuel you have already. Not at a computer at the moment

**Comment by seandenigris** [comment]
Fetching and pulling latest [Simple Persistence](https://github.com/seandenigris/Simple-Persistence) commit should solve it

**Comment by RalfBarkow** [comment]
@seandenigris I can confirm! Thank you very much.
